### ISSUE TITLE
Few chat

### ISSUE THREAD

**Issue by REDEMBER34** [m-shalenko/myteam-alertmanager-bot#1]
Hi. Can you help me  how i can defline a few chat in my configuration and defline in your code. I realy don't understand how it's work. 
Or i can add tags in my configuration. Please give me a few examples, it's realy help for me in understanding working it's app.

**Comment by REDEMBER34** [comment]
Please give me example configuration aletmanager.yml and manager.py, with a few  add chat_id

**Comment by m-shalenko** [comment]
@REDEMBER34 Hello! This was described in [README](https://github.com/m-shalenko/myteam-alertmanager-bot?tab=readme-ov-file#how-to-install), by the way. But sure, here is an example:
```yaml
# alertmanager example config
global:
  resolve_timeout: 5m
  http_config:
    follow_redirects: true
    enable_http2: true
  smtp_hello: localhost
  smtp_require_tls: true
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
  opsgenie_api_url: https://api.opsgenie.com/
  wechat_api_url: https://qyapi.weixin.qq.com/cgi-bin/
  victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/
  telegram_api_url: https://api.telegram.org
  webex_api_url: https://webexapis.com/v1/messages
route:
  receiver: vkteams-foo-alerts
  continue: false
  routes:
    - receiver: vkteams-foo-alerts
      group_by:
        - alertname
        - group
      matchers:
        - team="FOO"
      continue: true
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
    - receiver: vkteams-bar-alerts
      group_by:
        - alertname
        - group
      matchers:
        - team="BAR"
      continue: true
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
receivers:
  - name: vkteams-foo-alerts
    webhook_configs:
      - send_resolved: true
        http_config:
          follow_redirects: true
          enable_http2: true
        url: http://myteam-alertmanager-bot.example.com:8080/api/v1/push
        max_alerts: 0
  - name: vkteams-bar-alerts
    webhook_configs:
      - send_resolved: true
        http_config:
          follow_redirects: true
          enable_http2: true
        url: http://myteam-alertmanager-bot.example.com:8080/api/v1/push
        max_alerts: 0
templates:
  - /etc/vm/configs/**/*.tmpl
```
And start your bot with following ENV variables
```bash
export API_URL_BASE="https://api.vkteams.example.com/bot/v1/"
export BOT_NAME="<bot_name>"
export API_TOKEN="<bot_token>"
export CHAT_ID="<default_chat_id>"
export CHAT_ID_VKTEAMS_FOO_ALERTS="<chat_id_1>"
export CHAT_ID_VKTEAMS_BAR_ALERTS="<chat_id_2>"
cd app/
python3 manager.py
```
